[tool.poetry]
name = "ai-financial-analyst"
version = "0.1.0"
description = ""
authors = ["Alvaro Peña"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
